# Generated by Django 5.0.6 on 2024-05-30 19:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_provider_currency_alter_provider_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='polygon',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
    ]
