# Generated by Django 5.0.6 on 2024-06-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_provider_user_servicearea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='information',
        ),
    ]
