# Generated by Django 5.0.6 on 2024-06-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_servicearea_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['provider', 'id']},
        ),
    ]
